### ISSUE TITLE
Why aren't A8 - Insecure Deserialisation & A4 - XXE just part of A-1 Injection Attacks?

### ISSUE THREAD

**Issue by kerberosmansour** [OWASP/Top10#176]
A8 - Insecure Deserialisation & A4 - XXE, aren't those just injection attacks? In the past XXE was part of A1 see (https://www.owasp.org/index.php/Top_10_2013-A1-Injection), and count me as one of the people that could like it to remain so but expand the depth of the individual top ten to provide more detail. It does feel right that is in #1 issue rather than #4 on the list.

**Comment by raesene** [comment]
I'd agree here although if you're going to add deserialization and XXE in to Injections, then it would make sense to add XSS as well.

My personal opinion is that there's a small difference between XXE and these others in that with XXE the attacker is (ab)using a legitimate part of the functionality of XML, which is the inclusion of external entities.  If you compare with SQLi, XSS, Deserialization et al, those are somewhat different in that the injection abuses the parser rather than just misusing legitimate functionality.

**Comment by kerberosmansour** [comment]
@raesene I hear what you are saying but for me where it takes advantage of a parser or legitimate functionality, its an injection attack which allows an attacker to either run arbitrary code, and or exfiltrate data (in the case with some SQLi attacks)

As for the XSS comment, the risks for injection attacks are server side attacks, where as XSS would fall under client side attacks.

Remember whatever we add, other issues would be dropped, issues that would signal to developers they should not worry about anymore as most best practices just says follow the top ten. 

Put me on the camp of people that would prefer to have all encompassing fields e.g. A-1 so we do not drop category of attacks that still need to be addressed by developers.

**Comment by jmanico** [comment]
No, XXE is a access control issue. XXE is submitting a perfectly legal XML doc that uses DTD features like external references. You are not injecting into existing commands you’re submitting perfectly legal documents based on how your XML parser is configured.

Many, including myself, have made the mistake of calling XXE injection in the past.

--
Jim Manico
@Manicode

**Comment by raesene** [comment]
@kerberosmansour that's an interesting perspective on injection attacks (in the context of the Top 10) being server-side, with that added delineation it does make sense to split out XSS from the others. Perhaps some wording in A1 could mention that aspect.  @jmanico yep I agree with you there Jim, I think the split between A1 and A4 is whether it's legitimate functionality or not.

**Comment by kerberosmansour** [comment]
@raesene @jmanico the general point I was trying to make is can we consolidate those two issues (A8 & A4) into other parts of the top ten like A1 (Injection attacks) or A5 (access control)?

As mentioned here #177 if something drops from the top ten that we care about, developers might not consider them going forward, which means we might see a return of that issue in the data after all the hard work we have done with the community to avoid it. 

e.g. CSRF attacks might be down, but thats because we know how to avoid them and the community has done a good job addressing it. If it drops off the top ten the numbers might go up going forward.

This and Open redirection attacks is the reason I am asking, can we consolidate A4/A8 or do is it better to call those out specifically as separate items.

**Comment by sslHello** [comment]
Hi,
I'd see the difference is that all injections are attacks via the input of user data that is transfered as a value. The weakness is that this can break out from being a value to become an argument, statement or command. So it enters a different 'sphere' and 'attacks' the interpreter.
I'd say that XXE does not need 'injections' to any value field. You are able to add schema definitions, attribute definitions etc directly. In my opinion the issue is that the definitions, and types that you can add are not resticted. So you can even add external entities.

I see this as a sgnificant difference to justify beeing an individual risk. Additionally according to the data call it has a markable individual prevalence.
I hope you see that we've tried to have a general policy which issues are merged and which should be individual. For RC2 this had not always been an easy decision... .. there are only 10 places in the Top 10.
I hope this helps.
Cheers Torsten

**Comment by kerberosmansour** [comment]
Thanks Torsten, again I  would like to politely challenge if any of these specific vulnerabilities (A8 & A4), can be consolidated into other parts of the top ten (e.g. A1 or A5 etc..).

I think we got too transfixed with XXE and what type of an attack it constitutes. If we are saying it is an access control issue, then fine, can it be consolidated under access control? 

Same thing applies for Deserialization, are you ok with it being on its own or should it be in an all encompassing category?

**Comment by m8urnett** [comment]
@kerberosmansour the problem here is that the Top 10 is and always has been a loose mixture of broad categories and specific weaknesses, many of which overlap. I would argue that XXE is more a confused deputy attack than anything. But yeah it is also an access control issue and it is also a security misconfiguration. And even though it is technically valid XML, it has many of the same characteristics (and remediations) as injection attacks. And XSS, despite being an injection attack, has it's own category but SQLi doesn't. 

One solution is to make the list strictly categories or strictly vulnerabilities. But I think a better solution is to treat it as casual guidance and not treat it as an actionable checklist or policy driver. For actionable guidelines you should be using ASVS not the Top 10.

**Comment by vanderaj** [comment]
We have data for XXE in its own right. I'm happy for it to stand alone. @sslHello @Neil-Smithline @infosecdad let's discuss this item at next Friday's meeting, but I'm more than in the "we have data, it's in" camp.

**Comment by kerberosmansour** [comment]
@m8urnett You have hit one two good points, XXE does feel like more of a confused deputy problem (thoughts @jmanico ?). 

But more importantly the second point, has the top ten out grown its purpose, and should it be part of a larger document? It was just a top ten for web application risks, is this the best document to be a cornerstone for developer training for example? I know we won't solve this here, but should we provide recommendations on which OWASP documents to use, when...

**Comment by jmanico** [comment]
“Confused deputy” is a special form of privilege escalation so I call it an “access control problem” to make it easier to communicate with developers.

The OWASP Top Ten is cited in several regulations, so it sure does seem very important to me! 😎

**Comment by eoftedal** [comment]
XSS would make sense to put under A1 injection, but it also makes sense as a separate point due to its prevalence, but also due to the fact that some XSS vulnerabilities dont necessarily fit under injection (typically some types of DOM-based attacks).

We could apply this logic to XXE and Deserialization as well. We lift them out as separate top 10 entries to make sure they get noticed. 

Many vulnerabilities can fit into several categories. One could label XXE as Security misconfiguration as well, as it's about abusing a insecurely configured XML parser.

We could also have considered merging Insecure Direct Object References  with Deserialization and also add things like mass assignment to the same category, as they are all about the ability to  affect access to objects, access to internals of objects, creation of objects etc.

**Comment by jmanico** [comment]
So you’re saying just make one category called AppSec and throw everything under that? The OWASP Top 1? 😎

But seriously, the many-to-many nature of this ontology is good to point out.

**Comment by Neil-Smithline** [comment]
The T10, largely an appsec visibility document, is designed to highlight the most important appsec issues for the next ~3 years. For example, I think it makes sense to separate XSS from Injections in general. XSS continues to be a widespread and devastating problem that is frequently handled by different developers (front-end v. back-end).

**Comment by eoftedal** [comment]
He he, @jmanico, the point was that it's always possible to merge stuff and split stuff out :)

I think @Neil-Smithline summarized it well. Highlighting should be the goal of the OWASP Top 10.

**Comment by global4g** [comment]
If A1 Injection doesn't cover all the injections then can we include the implied types in the name. For e.g. call it  A1 - SQL/OS/LDAP Injection ?

**Comment by infosecdad** [comment]
We can consider revisiting in the next version, but for 2017 this is how it is going to be presented.
