### ISSUE TITLE
Consider putting greater emphasis on weak/no TLS 

### ISSUE THREAD

**Issue by Neil-Smithline** [OWASP/Top10#205]
See @ivanristic's [tweet](https://twitter.com/vanderaj/status/921805141967224833). Little or no mentioning of lack of TLS in A6 seems inadequate to address such a large problem. For example see [Hardenize dashboard](https://www.hardenize.com/dashboard/global-top-sites/).

**Comment by ivanr** [comment]
@Neil-Smithline Thanks for opening this ticket and keeping me honest :) My point is that inadequate protection of the transport layer is a huge problem. Even among the top 500 sites the situation is not great, and I'd guess that it's much morse among less visited sites. We have sites without encryption,—where TLS is not used at all—then a _lot_ of sites without HSTS or HSTS preloading, many with mixed content issues, even more with insecure session cookies, and so on. We, as a community, have made a lot of effort in recent years to improve things, but there's still a lot left to do. There is only one outcome that will ensure security, and that's a 100% encrypted Web.

It gets worse once we move outside HTTP. When it comes to SMTP, encryption is entirely opportunistic and easily broken by MITM attacks (because virtually no one checks that valid certificates are provided or requires encryption for email transport). And so on.

The only way to fix this problem is via a joint effort to raise awareness, and OWASP Top 10 should be a part of it.

**Comment by vanderaj** [comment]
Torsten, I totally 100% agree with @ivanr comment. We need to address this prior to Golden Master. Let's talk about this next Friday, but I'm allocating you to this ticket. I'm sorry I missed this during QA.

**Comment by sslHello** [comment]
@ivanr - Ivan, thank you very much for your comment and suggestions.
@vanderaj - Andew, I'd suggest that we try to find a better balance between  data at rest and data in move (TLS) in all boxes (e.g. Impacts, Is the Application Vulnerable?).

Ivan, I'd loved to add some more advice about TLS, too. But I haven't found any place to get some space for something like Perfect Forward Secrecy, yet.
HSTS had been included in A3 'How to Prevent' and in A6 'Is the Application Vulnerable?' I have extended the latter to 'Security Headers'.
And yes, https is sometimes badly configured but all other protocols might be a nightmare. The sadest of this is that this is mostly caused by default configurations...
We try to get readers more interested in protecting their senitive data using encryption correctly. We'd like to attract them to read the references where they can get more help, e.g. [OWASP Cheat Sheet: Transport Layer Protection](https://www.owasp.org/index.php/Transport_Layer_Protection_Cheat_Sheet), [OWASP Testing Guide: Testing for weak cryptography](https://www.owasp.org/index.php/Testing_for_weak_Cryptography).
Cheers Torsten
PS: I am also maintaining the Cheat Sheet 'Transport Layer Protection' and I am compiling a draft Cheat Sheet 'TLS Cipher String'.

**Comment by ivanr** [comment]
@sslHello FYI, I already maintain several comprehensive resources that explain in detail how TLS and PKI should be configured. For example, there's the SSL/TLS Deployment Best Practices https://github.com/ssllabs/research/wiki/SSL-and-TLS-Deployment-Best-Practices and also my free OpenSSL Cookbook (which includes the former document in the appendix) https://www.feistyduck.com/books/openssl-cookbook/ So why recreate another document (or even documents) when good reference material is already freely available?

**Comment by sslHello** [comment]
@ivanr Ivan, thank you, yes I do know and have them both here. 
The 'cipher string' section of the Transport Layer Protection Cheat Sheet needs already a lot of space. I liked to expand it with recommendations by scenarios. So I think it's better to do this in an additional subsidiary Cheat Sheet than to make the Transport Layer Protection Cheat Sheet again bigger.

**Comment by sslHello** [comment]
@ivanr - Ivan, I've obtained some more space for TLS and enhanced the emphasis on TLS. 
I hope you like it better now.
Thanks and cheers Torsten

**Comment by sslHello** [comment]
Note: Tried to keep changes from #71 while moving some text from 'How to Prevent' to Scenario 3 to get space there.

**Comment by sslHello** [comment]
fixed
