### ISSUE TITLE
Data Analysis - Feedback

### ISSUE THREAD

**Issue by kerberosmansour** [OWASP/Top10#231]
Firstly nicely done, and I quite liked the Incident Rate Per CWEs

![image](https://user-images.githubusercontent.com/13433538/31865423-cdbc5546-b766-11e7-96df-5408007f39d5.png)

- Should we reach out to MITRE for the vulnerabilities without CWEs?
- What is the methodology to decided between incident per CWE and community feedback? i.e. once we have the data how do rate the top ten?
- Some responses were not easily analyzed the way they were collected like language, region etc..
- Analysis of vulnerabilities by language would be interesting with more granular data
- I separated the CWE number and the vulnerability/issue name into different fields
- Vendors have listed lack of defence against automated attacks, which is something to make note of. It won't be picked up easily or via SAST/DAST testing.

I took a look at the data analysis, in fact I forked the top ten for that, my findings (which are on github), were more basic, but I thought I'd share them
https://github.com/kerberosmansour/Top10/tree/master/2017/datacall/submissions/Data 

![image](https://user-images.githubusercontent.com/13433538/31865357-d4b69e66-b765-11e7-8af6-a651d0d59983.png)

If I Remove the top three issues, I get this:
![image](https://user-images.githubusercontent.com/13433538/31865369-f89358f6-b765-11e7-807d-5a3d9bf65d8c.png)

**Comment by infosecdad** [comment]
> Should we reach out to MITRE for the vulnerabilities without CWEs?
At some point, yes. 

> What is the methodology to decided between incident per CWE and community feedback? i.e. once we have the data how do rate the top ten?
The Top Ten is rated by the risk calculations described in the document. Incident rate is only one part of the calculation.

> Some responses were not easily analyzed the way they were collected like language, region etc..
Very true, one thing I'm hoping for is a more formalized/standardized datacall for 2020

> Analysis of vulnerabilities by language would be interesting with more granular data
Absolutely agree. I would love to be able to collect enough detailed data to be able to say things like applications built with this specific language/framework have these top 5 problems. However, we are going to need a cultural shift for that to happen. We managed to get ~40 organizations to contribute, but I know of several that didn't/couldn't because of concerns about what someone might do with the numbers they disclosed.

> Vendors have listed lack of defence against automated attacks, which is something to make note of. It won't be picked up easily or via SAST/DAST testing.
Honestly, I'm not entirely sure what the root of that is. The anti-automation CWE didn't get a lot of selection in the industry survey, nor is there a lot of data supporting it. I can't tell if there are just a small number of passionate people talking about it or if we have trouble finding it. Hard to say.

I see you've also probably figured out why we aren't using frequency data like in the charts above. Looking at the number of occurrences often paints a very inaccurate picture. XSS will massively dominate those graphs for a while yet. It is the only CWE that every contributor in the main table found. It also has a tendency to be found many times within an application. Fortify averages 400+ occurrences per app and Veracode is around 250 occurrences.

Thanks for putting the time in to review and comment!
