### ISSUE TITLE
rename "apps" to applications in the document text

### ISSUE THREAD

**Issue by securestep9** [OWASP/Top10#243]
Numerous changes should be made to give the document more professional style. The only acceptable case to use the word "app" is in the context of a "mobile app" or "smartphone app".

Some examples where this needs fixing (there are way too many to list here)

**enterprise app** portfolio -> enterprise **application portfolio**

depending on the **domain of the app**, this may allow money laundering -> depending on the domain of the **application**, this may allow money laundering

The **app server admin** console is automatically installed and not removed -> The **application server** administrative console is automatically installed and not removed.

**Comment by Neil-Smithline** [comment]
Thanks for the feedback. I believe I've gotten most of them. Due to space constraints, I've left `app` in:

- **Tables:** The phrase `app specific` is used in the table at the top of each T10 and a few other tables.
- **A6-2017:** Examples in the context of `app server` or `sample apps` of the app server.

That seems like the right compromise between clarity and space.
