### ISSUE TITLE
GM - A9:2017 Using Components with Known Vulnerabilities

### ISSUE THREAD

**Issue by ossie-git** [OWASP/Top10#271]
"This issue is detectable by the use of scanners such as retire.js and header inspection, but verifying if it is exploitable requires an attack of some description." -> "Some scanners such as retire.js help in detection but determining exploitability requires additional effort."

"If any of your software out of date?" -> "If any of your software is out of date"

"If you do not know if they are vulnerable. Either if you don't research for this information or if you don't scan them for vulnerabilities on a regular base." -> Scanners provide limited coverage.  I would re-word to: "If you do not know if you are vulnerable due to you not scanning for vulnerabilities regularly and sub-scribing to security bulletins related to the components you use."

The problem with mentioning the Versions Maven Plugin is that it doesn't tell you if there are security-related issues related to the packages you use.

"Continuously monitor sources like CVE and NVD for vulnerabilities in your components. Use software composition analysis tools to automate the process." -> I would add: "Subscribe to email alerts for security vulnerabilities related to components you use."

**Comment by Neil-Smithline** [comment]
So I went for something even simpler with: "If you do not know if they are vulnerable. Either if you don't research for this information or if you don't scan them for vulnerabilities on a regular base." -> "If do not scan for vulnerabilities regularly and subscribe to security bulletins related to the components you use." What do you think?

I decided to leave the Maven versions plugin in place because the text doesn't say that it will prevent the problems. It just states that you need to inventory your components. The next bullet talks about how to use that inventory.

**Comment by ossie-git** [comment]
+1.  Sure.  I think both make sense.
