### ISSUE TITLE
GM: Acknowledgements

### ISSUE THREAD

**Issue by ossie-git** [OWASP/Top10#276]
Please replace my handle (ossie-git) with my real name: Osama Elnaggar

Thanks.

**Comment by Neil-Smithline** [comment]
This is a very reasonable request, and you've been super helpful, but we'll need to discuss our general policy about this. It will take a few days before we can get a chance to discuss. Thanks again for your efforts!

**Comment by ossie-git** [comment]
I actually sent this by mail to Andrew on the 18th before R2 was released but it looks like he was too busy preparing R2.

**Comment by ossie-git** [comment]
Also, I'm already on the contributor's list @Neil-Smithline.  Search in https://github.com/OWASP/Top10/blob/golden-master/2017/en/0xd1-data-contributors.md for ossie-git.  You'll find me.  All I'm requesting is to replace my handle with my name.  Strange that something like this requires a discussion.

**Comment by Neil-Smithline** [comment]
Hey Osama - The reason I don't want to change your GitHub username to your real name is because we are not sure how to do that for everyone. First not everyone uses their real names. So it wouldn't be fair to do that just for a few people. There may also be people who don't want their real name used. It would just be difficult to track down everyone in time to ask if they mind us using their real name.

That said, the co-leaders have decided that we're going to thank a handful of people by name. This is keeping with tradition of past T10s (see [2013 example](https://www.owasp.org/index.php/Top_10_2013-Introduction)). We all agree that you will be one of the one's that we'll call about by name. So we're going to leave your GitHub handle, but also add your name.

We want to thank you for all of your help!!

Neil

**Comment by Neil-Smithline** [comment]
Thanks again for all of your help Osama!

**Comment by ossie-git** [comment]
Cool.  Thanks.
