### ISSUE TITLE
A7 should be removed as it is promoting commercial interests

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#32]
I've heard a lot of criticism about the proposed OWASP top ten from the pentesting community:
The biggest is that A7 sounds like a thinly-veiled ploy to promote IPS/WAF products.  Other people's paraphrased words, not mine, but I do tend to agree. I seem to recall similar concerns were raised about A9 last time around, since there were commercial products that tackle this problem being sold by some involved in the project.  Do we want the pentesting community to see the top 10 as being hijacked by commercial interests?
Timothy D. Morgan

**Comment by Neil-Smithline** [comment]
@AccelaEV I apologize if you're the wrong "Timothy D. Morgan". I took a chance as I don't want to exclude the original author of the comment.

**Comment by ecbftw** [comment]
Based on descriptions of this item I read *after* the draft was published, I can appreciate elements of it.  But they weren't represented in the draft document itself in any clear way.

Things I could get on board with would be items that fall under the category of "Lack of automated attack mitigation".  So login forms that lack captchas, authentication interfaces that don't throttle thousands of clearly malicious requests, etc.  If a single client sends you thousands of bad OAuth tokens in a row, should the application do something about that?  Sure, that probably would be a good idea.  But we need good guidance on how to do this, because you quickly get into the realm of DoS mitigation and that's a hard problem.

However, I'm staunchly opposed to any item in the Top 10 where the only practical "solution" is to throw a security product in front of the application.  We, as an industry, already spend far too much on products that don't prevent breaches.

**Comment by vanderaj** [comment]
This risk is going to be removed as per community feedback at the Project Summit, survey data and revised data call. Thank you for your input on this matter.
