### ISSUE TITLE
CSRF defenses clarifications needed 

### ISSUE THREAD

**Issue by securestep9** [OWASP/Top10#321]
We have on  
Page 5: _"Frameworks commonly include CSRF defenses, with < 5% of all apps, now `#13`."_ 

First of all "apps" needs changing to "applications" as per issue ref:  #320 

Secondly, since we mention some mysterious "Frameworks" this needs some examples of  these frameworks which mitigate CSRF, for example OWASP CSRF Guard 

I propose we rewrite the CSRF bit on Page 5  as follows:

"Frameworks commonly include CSRF defenses,  less than 5% of the data set supports this issue today, now `#13`. For example see: [OWASP CSRF Guard](https://www.owasp.org/index.php/Category:OWASP_CSRFGuard_Project)"

CSRF is also mentioned on Page 14 in XSS:
_"Attackers can use XSS to defeat any automated **CSRF** defense the application might employ."_

 I propose that in References/OWASP section on Page 14 at the bottom of OWASP references we add the reference to [OWASP Cheat Sheet: CSRF Prevention ](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet)

**Comment by riramar** [comment]
I'd also include something specific about this https://www.owasp.org/index.php/SameSite

**Comment by Neil-Smithline** [comment]
As CSRF is not in the 2017 T10, we are very limited on the amount of space that we have to discuss it. By "very limited" I mean that we have _one line_ in the PDF version on the `RN Release Notes` page. And the start of that line has to be the name of the risk from the 2013 T10. Any more space and we'll have to delete another line from that page as it's full. 

With that in mind, there's very little we can do. We already had fixed "apps" to "applications" (which eats up more space!). I've changed it so that it now reads:
> **A8-Cross-Site Request Forgery (CSRF)**, as many frameworks include [CSRF defenses](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)), it was found in only 5% of applications.

The now-linked-to OWASP CSRF page lists relevant frameworks - thanks for the suggestion. I generally fixed the grammar for that line and the A10 line below it as they were a bit messy (thanks again!).

I do not think that the CSRF cheat sheet reference belongs in A7 as that page is about preventing XSS, not CSRF. If a user reads the line about CSRF and doesn't know what it is, they can use Google to figure it out.

**Comment by Neil-Smithline** [comment]
@riramar - I'm not familiar with the SameSite option. From my quick research, it looks like that it can help minimize the damage done by an XSS attack by preventing an attacker exfiltrating SameSite cookies. Is that correct? Does it have any other relationship to XSS?

**Comment by Neil-Smithline** [comment]
After reading [this](https://security.stackexchange.com/a/121986/10885), I've decided that SameSite doesn't protect against XSS or ameliorate the damage done by an XSS attack, so I'm not including it in the XSS page.
