### ISSUE TITLE
A6: No cryptographic risks

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#34]
Another concern I have is that there's very little emphasis placed on cryptographic flaws in web applications.  Maybe 1/3 of all web applications I look at have some kind of broken crypto in URL tokens and other tokens exposed to users.  Broken "Bearer" tokens in OAuth, POA vulnerabilities in password reset tokens, etc.  It is disappointing that the top 10 still mention these anywhere, because awareness is needed.  To be clear, I'm not talking about TLS ciphers and password hashing.  I'm talking about application crypto vulnerabilities that are much more serious and practically exploitable.

6.	Timothy D. Morgan

**Comment by jmanico** [comment]
Agreed - buff out "data protection" to address this?

--
Jim Manico

**Comment by Neil-Smithline** [comment]
@AccelaEV I apologize if you're the wrong "Timothy D. Morgan". I took a chance as I don't want to exclude the original author of the comment.

**Comment by ecbftw** [comment]
A key element to the vulnerabilities I'm talking about is that they aren't typically about the *exposure* of sensitive data.  They are about allowing an attacker to *modify* it.  No one cares if someone can decrypt your OAuth bearer token, since there's usually no sensitive data there.  What they *do* care about, is if you can forge a fake bearer token that the application accepts.  CBC padding oracle vulnerabilities are still pretty common, but so are unprotected ECB ciphertexts and stream ciphers with bad IVs.  These kinds of issues cross the boundary between "crypto" issues and "authentication" issues.  Not sure the best place for them in the top 10.

**Comment by sslHello** [comment]
Hi,
thank you for you valuable comments.
I have updated the 'How do I Prevent' section to 
"* Make sure you encrypt all sensitive data at rest or transferred via clients, e.g. cookies, tokens."
I am keeping the the other issue about data could be modified for one of the other sections. I'll come back to it later.
I hope this solves your findings.

Cheers
Torsten

**Comment by sslHello** [comment]
Hi, 
thanky you for your comment.
I've extended Scenario Nr 2 to add crypto issues and the risk about modifying data:
"Scenario #2: A site simply doesn’t use or enforce TLS for all pages, or if it supports weak encryption. An attacker simply monitors network traffic, strips or intercepts the TLS (like an open wireless network), and steals the user’s session cookie. The attacker then replays this cookie and hijacks the user’s (authenticated) session, accessing or modifying the user’s private data. Instead of the above he could also alter all transported data, e.g. the recipient of a money transfer."
Hopefully it is not overcharged, yet....

I hope this solves your findings. Issue resolved. Please review updated text.
