### ISSUE TITLE
A4: Add 'by using solely primitive data types' to JSON? 

### ISSUE THREAD

**Issue by sslHello** [OWASP/Top10#341]
'How to Prevent':
'Whenever possible, use a less complicated data format such as JSON.'
-> 'Whenever possible, use a less complicated data format such as JSON by using solely primitive data types.'

**Comment by Neil-Smithline** [comment]
Torsten - I'm not sure what the added text means.

**Comment by vanderaj** [comment]
There's a total of six primitive data types in JavaScript (boolean, null, undefined, number, string, symbol and object.

As one of these is "object", so, this statement doesn't make a lot of sense. I'll try to make this a bit better a little later whilst I have a think about it, but I'm leaning towards simplification of the language for clarity rather than asking people to do something that doesn't make a whole lot of sense.

**Comment by Neil-Smithline** [comment]
I'm not sure that we want to make this change as I think the concept is a bit complicated to squeeze into a single bullet. Perhaps you can come up with some spectacular wording, but perhaps this is just good enough.
