### ISSUE TITLE
A10 Is out of place. Replace with deserialization bugs

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#35]
Finally, what exactly is A10?  Um... it's almost like an answer to a *different* question.  The top 10 has traditionally been an answer to "what kinds of flaws might affect my application".  This is an answer to the question "where in my application might there be flaws".  It seems like filler.  why not call out deserialization bugs here instead?  People get badly owned by those.  They actually matter.

6.	Timothy D. Morgan

**Comment by Neil-Smithline** [comment]
@AccelaEV I apologize if you're the wrong "Timothy D. Morgan". I took a chance as I don't want to exclude the original author of the comment.

**Comment by ecbftw** [comment]
Deserialization bugs have had a serious impact on the world.  Struts alone is responsible for a huge number of breaches.  While Java is a hotspot for this, PHP has serious deserialization problems too.  Ruby isn't immune.  

Developers tend to treat objects they are passing back and forth as pure data, but due to awful choices by developers of the underlying serialization libraries, it turns out that this data is really code in many cases.  Awareness needs to be raised both with developers, but also with the developers of platforms, so they can redesign these interfaces in the long term.

Note that while the number of deserialization vulnerabilities is far smaller than something like open redirects, but deserialization is many many orders of magnitude worse.  Ever heard of a breach starting as an open redirect?

**Comment by Neil-Smithline** [comment]
Based on the results of the industry survey ([background on survey](https://owasp.blogspot.com/2017/08/owasp-top-10-2017-project-update.html)), API vulnerabilities will not be in the Top-10. Where appropriate, mentions of API vulnerabilities will be added to other risks.

Whether deserialization vulnerabilities is included or not will be based on the survey.
