### ISSUE TITLE
A10 - "Underprotected APIs" is not a separate category

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#39]
- This category can be summarized to "Check the OWASP Top 10 for API endpoints too". This isn't a category of vulnerability. This should be integrated through all the other vulnerabilities by specifically mentioning checking API endpoint too. It might also be better to add a section in the document titled "What to test ? Where to look for vulnerability ?". 

8.	Olivier Arteau

**Comment by Neil-Smithline** [comment]
FYI @HoLyVieR

**Comment by irbishop** [comment]
I had the same thoughts about A10, instead of starting a separate thread I'll include them here.

Is the point of A10 to inform people that API's suffer from the same vulnerabilities as traditional web applications?

The examples provided are repeats of other Top10 issues with a different target - the API instead of the Application.

A10 Scenario 1:
 _The attacker sends legitimate credentials, but another user’s account number, gaining full access to the other user’s account._

A4 Scenario 1:
_An attacker simply modifies the ‘acct’ parameter in the browser to send whatever account number they want. If not properly verified, the attacker can access any user’s account._

A10 Scenario 2:
_The API parses out this “transactionid” value as a string and concatenates it into a SQL query, without escaping or parameterizing it._ 

A1 Scenario 1:
_An application uses untrusted data in the construction of the following vulnerable SQL call:

String query = "SELECT * FROM accounts WHERE custID='" + request.getParameter("id") + "'";_

Would it be simpler to point out that API's can suffer from essentially all the same issues that a traditional Application may suffer and the top 10 applies to API's as well as Application?  Is it necessary to have a separate top 10 entry to say "API's are vulnerable to the other top 10 issues, here's an example of how it's vulnerable to Injection attacks or Access Control issues"?

This would also allow another top 10 entry, such as unvalidated redirects and forwards which is still far too common, to have, or maintain an entry in the top 10.

**Comment by jmanico** [comment]
One of the reasons I like A10 is because API's serve a infrastructure role that web apps rarely do. I'm talking identity services that run a whole company or "back end data services on a private network" that are common to REST deployments.

Many folks build API's with no security in "trusted zones" that serve as data services - which is a massive and common anti-pattern.

The vulns are the same. But the impact is often very high.

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by gilzow** [comment]
> The vulns are the same.

That was @irbishop's point: _A10 Underprotected APIs_ doesn't introduce a new vulnerability or risk, only a new type of application that is vulnerable to all of the other risks in the A1-A9.

**Comment by jmanico** [comment]
And my point is, while the vulns are the same, the risk profile and
organizational impact are often VERY different.

Also, there are things that API's handle a lot more than web apps
(untrusted XML/JSON parsing which has led to serialization issues which
are hard to handle). Also, identity verification is often very different
in modern web services.

- Jim

**Comment by gilzow** [comment]
Shouldn't we then be introducing new risks into the top 10 that need addressing, like serialization, instead of specific class of application?

**Comment by Neil-Smithline** [comment]
I think that there is debate about what the word "risk" means @gilzow. A risk could be a specific type of vulnerability, an attack vector, a process deficiency, or anything else that adds uncertainty to the business. While not defining exactly what a risk is, the 2017 Top 10 will be using something close to a class of vulnerabilities. I think that's more inline with what you are suggesting. That said, it is far from non-controversial. For example, see #84.

**Comment by gilzow** [comment]
Agreed.  This list has always been referred to as the top 10 "risks" but in reality, has really been mostly about vulnerabilities (injection, broken auth, broken session management, etc.).  I'll amend my earlier statement to say that I consider weak/broken deserialization a vulnerability, not a risk.  If nothing else, this highlights that there needs to be a clear definition of "risk", "vulnerability" and "security weakness" as those three terms are used heavily in the document, but never defined.  

My particular hang-up with API is that an API **is** an application. So saying "Underprotected APIs" is equivalent to saying "Underprotected Applications".

**Comment by borischen** [comment]
de/serialization vulns in general is something good to consider for the top 10 rather than unprotected apis, for the reasons mentioned above. Since there is the removal of "Insufficient Attack Protection", "Underprotected APIs" sound to be in the same type of risk. Either both should be in the top 10, or neither. Since the top 10 #84 sounds like the scope is now vulns, then underprotected apis is definitely better suited for "OWASP Top 10 Defences"

**Comment by jmanico** [comment]
I'm more than willing to move away from unprotected API's for what it's
worth. I like it but I'm not tied to it.

I especially like the idea of putting "untrusted deserialization" and/or
XXE in the Top Ten.

- Jim

**Comment by borischen** [comment]
Unsure if this is the right process, but opened up #92 to track

**Comment by Neil-Smithline** [comment]
If you haven't already, we'd appreciate you taking the survey. That's the best place to register you're opinions on what's most important. https://docs.google.com/forms/d/e/1FAIpQLSdy-ok2o_BBHsZn0r5WfwxOkCv1CQ4nKZ8VSmD6bYq-du22hg/viewform

**Comment by Neil-Smithline** [comment]
Based on the results of the industry survey ([background on survey](https://owasp.blogspot.com/2017/08/owasp-top-10-2017-project-update.html)), API vulnerabilities will not be in the Top-10. Where appropriate, mentions of API vulnerabilities will be added to other risks.

We'll reply to the discussion about deserialization vulnerabilities in #92.

Thank you everyone for the feedback!
