### ISSUE TITLE
Make T10 entries unique and non-overlapping 

### ISSUE THREAD

**Issue by thesp0nge** [OWASP/Top10#4]
Hi folks. Imagine this 2 scenarios:

* you find an API vulnerable, let say do SQL injection. Is it a A1, A7 or A10 risk category?
* you find an API vulnerable to remote code execution. Which is the one to use A7 or A10?

**Comment by jmanico** [comment]
We've had the same problem with XSS since it's a form of injection. "Both" is an acceptable answer, IMO.

--
Jim Manico
@Manicode

**Comment by thesp0nge** [comment]
IMHO, "both" can't be a good answer when trying to draw a top 10 risk categories.
Think at your awareness session, how do you explain when a risk is A7 and when is A10?

**Comment by jmanico** [comment]
This has been the state of the OWASP TopTen for years. (Again, XSS is a form of injection so I've been using "both" [2013 A1 and A3] to describe this risk for years).

It's very simple to mention both. I don't see the problem. 

And let's get really crazy here. Imagine an XSS payload that steals the session cookie. Now we have a specific attack that falls under 2013 A1, A2 and A3!

Or how about an XSS payload that steals the session due and is viable due to a important filter disabled in configuration? There is a scenario where one situation falls under 2013 A1, A2, A3 and A5. 

The relationships of attacks or risks to T10 categories is many to many.

Aloha,
--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by thesp0nge** [comment]
XSS is a form of injection but the target is very different (browser vs backend). So it can be good to distinguish it between A1. 

But A7 and A10 are almost identical (and they are also the topic of my question). So, again in one of your awareness sessions how do you describe the difference between Insufficient attack protection and Unprotected API?

True to be told, since a vulnerability is exploited, everything is "Insufficient attack protection", IMHO

**Comment by jmanico** [comment]
In my mind A7 and A10 are vastly different. I don't understand how you see them as similar, please tell us more.

Since many webservices are stateless as well as other differences; defending them can be quite different in certain security areas. I'm fond of bringing light to the problem of folks deploying internal webservices with no AuthN, AuthZ or transport security. It's a systemic problem. There is plenty of data backing this problem.

However, I do not think we need to shed light on missing attack detection. The sample data sets have absolutely zero evidence of this need. Zero. It was pulled out of the air and reeks of selling product. Please read https://nvisium.com/blog/2017/04/18/musings-on-the-owasp-top-10-2017-rc1/ for a more in-depth analysis of the data and choices made.

Aloha,
--
Jim Manico
@Manicode

**Comment by thesp0nge** [comment]
> In my mind A7 and A10 are vastly different. I don't understand how you see them as similar, please tell us more.

Jim, I do understand you disagree with me, that's why I asked "how would you describe the difference between Insufficient attack protection and Unprotected API?"

I think A7 is a super set of A10. A7 tells about an application or API that fails in detecting an attack. The A10 tells about an API that is unprotected. I mean, can we agree that the border line is a foggy grey zone?

Otherwise, maybe I misunderstand, in this case please someone explain me better. My task, as all of ours, is to tell the top10 stories to people not so trained in appsec and, in my experience, they need properly defined borders to better understand stuff.

**Comment by jmanico** [comment]
I personally do not see at how A7 and A10 are related, other than how A7 is related to all of AppSec. A7 is not (at all) API specific and covers web apps, too.

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by thesp0nge** [comment]
Fine. You explained your position very well. You disagree. But "how would you describe the difference between Insufficient attack protection and Unprotected API?"

>A7 is not (at all) API specific and covers web apps, too.
That's why I said A7 is a superset of A10.

**Comment by davewichers** [comment]
As Jim said, A7 and A10 are vastly different. A10 is about avoiding risks
A1-A9 in APIs.  A7 is about a specific situation where an application does
not automatically detect attacks, nor have any ability to respond when an
attack is detected. A7 also includes the ability to quickly (either
temporarily or permanently) patch a vulnerability that is discovered. This
is what we mean by the term "attack protection".

If this is not obvious after further consideration, please help us clarify
these differences by suggesting specific changes to the wording of A7
and/or A10 to make this more clear to everyone.

Thanks, Dave

**Comment by Calico90** [comment]
> As Jim said, A7 and A10 are vastly different

I'd like to refer to the release notes stating: 

> NOTE: The T10 is organized around major risk areas, and **they are not intended to be airtight, non-overlapping, or a strict taxonomy.** Some of them are organized around the attacker, some the vulnerability, some the defense, and some the asset. Organizations should consider establishing initiatives to stamp out these issues. **Source**: https://www.owasp.org/index.php/Top_10_2017-Release_Notes

Altough I'd rather would see it non-overlapping at least it's described that that isn't the case.

**Comment by Neil-Smithline** [comment]
I view the T10 as a checklist that engineers need to think about during development (and increasingly during deployment and operations). With that in mind, having overlapping entries isn't problematic.

**Comment by vanderaj** [comment]
As we have analysed the date, created a new ordering, and pretty much achieved the goal of the OP, I'm closing this issue.
