### ISSUE TITLE
Is the word order correct?

### ISSUE THREAD

**Issue by JZDLin** [OWASP/Top10#441]
In **A2: Broken Authentication** >>> in section **Is the Application Vulnerable?** >>> in para 5 >>> Uses plain text, encrypted, or **_weakly_** hashed passwords (see A3:2017-Sensitive Data Exposure).

Is it correct position of the word **weakly**?
May be it should be like this >>> Uses plain text, **weakly** encrypted or hashed passwords ???

**Comment by shoeper** [comment]
Maybe adding another weakly before encryption would make it more clear, but I think it is meant like encrypted passwords are a security issue, because they can be decrypted. Strongly hashed passwords cannot be decrypted which should be targeted.

So it is correct:
 * plain text passwords are an issue
 * encrypted passwords are an issue (no matter how good or bad the encryption is)
 * weakly hashed passwords are an issue (they can be brute-forced or even looked up in rainbow tables)

Or the other way around ONLY strongly hashed passwords are no issue.

**Comment by JZDLin** [comment]
Thanks, for your comment. It sounds reasonable.
