### ISSUE TITLE
Suggestions to add: insecure design - description and how to prevent

### ISSUE THREAD

**Issue by okdt** [OWASP/Top10#541]
I think you are missing the essential point in the part about the causes of "insecure design." I have drafted the following text for your reference.

> Description (add)
> One of the factors that contribute to insecure design is the lack of business risk profiling inherent in the software or system being developed, and thus the failure to determine what level of security design is required. As a risk profile, you should at least consider analyzing the compliance that the system in question must adhere to, the threats it will face, and the problems in operating the system in its current state. These will give you solid guidance and motivation on what approach to choose to design securely.
> 
> How to Prevent (add)
> Risk profiling is a good way to determine the expected security features of your software.

**Comment by efkay88** [comment]
My intepretation of Secure by Design: 
Secure by design (SbD), means that products/services and capabilities have been designed to be foundationally secure.

The secure by design approach ensures security considerations are addressed at every phase trough the software life cycle process. Ideally SbD engagement begins early in the design phase and embeds security in the service high level design and integrates security into software development and deployment cycle. It also should reveal (based on the risk appetite/profile of the assets) which security controls are required during runtime: WAF, Backup, Key/Credential Management etc. (with KPIs matching the business need to guarantee a proper efficiency and effectiveness)

With that I would suggest to declare security by design as an overall risk which aims not only to mitigate the OWASP Top 10 vulnerabilities (WEB/API) but also identifies architecture antipattern (high-availability, disaster recovery, insecure network configuration, insecure CI/CD tooling) and insufficient processes around CI/CD pipelines,  user access management, incident management etc. 

Main Goal:  Detect fast → fix early (minimize effort and costs)

Maybe a clear definition of Design in the context of web application can help the community to distinguish between architecture, process and software design as well? 

I see insecure design as a general risk (not a vulnerability).

**Comment by jmanico** [comment]
WAF’s are never required for security. Fix your damn, damn code people.

**Comment by okdt** [comment]
https://owaspsamm.org/model/design/threat-assessment/stream-a/


FYI: 
"Application Risk Profile
Benefit

Ability to classify applications according to risk"

**Comment by infosecdad** [comment]
Thank you for the feedback, we have incorporated some of it in A4:2021
