### ISSUE TITLE
Leave XSS as risk category

### ISSUE THREAD

**Issue by owasp-tobias-glemser** [OWASP/Top10#542]
While I understand the approach (I've always been talking about clientside and backend/server injection), the risks from clientside and serverside injection attacks are different. Therefore I suggest to leave XSS as own category.

- Clientside is a risk for the user of the app
- Serverside is a risk for the application owner

Further, countermeasures, testing etc is different. So lets get rid off SSRF ("industry professionals are telling us this is important, even though it's not illustrated in the data at this time.") and make XSS great again.

**Comment by jmanico** [comment]
I agree that XSS should remain its own category in particular because the defense is so different than other forms of injection.

To stop XSS we need:

Output encoding
HTML Sanitization
Use of safe JS functions
HTTPOnly cookies
Content Security Policy
Trusted Types

Why does XSS mandate these defenses when SQIi does not? Cause SQLi is easy to fix with a parameterized query. XSS is radically different for developers. This is why XSS appears so much.

**Comment by infosecdad** [comment]
Thank you for the feedback, but XSS will not be a standalone category in this Top 10 release.
