### ISSUE TITLE
Suggestion: Consider removing A4 Insecure design and adding malicious file upload instead

### ISSUE THREAD

**Issue by Gilc83** [OWASP/Top10#564]
In the following blog, the author commented on the top 10 draft and had some good points:
https://danielmiessler.com/blog/thoughts-on-the-owasp-top-10-2021/

I want to focus on the "insecure design" issue. As the post states, this is a generic topic that includes most of the other parts of OWASP top 10. In my opinion, it is like writing "insecure code" which many other security problems mentioned in OWASP top 10 are derived from.
Even the examples currently mentioned in the insecure design documentation, can be easily categorized as other issues:
- CWE-209: Generation of Error Message Containing Sensitive Information - can be categorized as A05 security misconfiguration
- CWE-256: Unprotected Storage of Credentials - clearly a A02 cryptographic failure issues
- CWE-501: Trust Boundary Violation - A01 broken access control
- CWE-522: Insufficiently Protected Credentials - A02 cryptographic failure issues

I think this category makes OWASP top 10 confusing and it won't be referred a lot.

On the other hand, what I keep finding missing from OWASP top 10 over the years is the malicious file upload vulnerability, and file storage issues in general. I don't know the exact data you collected, but in the company I work in (CYE, cyesec.com) we see it from time to time, and the consequences of such a vulnerability **could be catastrophic** and lead to RCE and complete system compromise.
I cannot think of any good reason that insecure deserialization, which is pretty framework specific, is part of OWASP top 10 while malicious file upload which can be just as catastrophic and is not framework specific, is not. I also find it hard to think of a good reason the open redirect and CSRF were part of OWASP top 10 while malicious file upload which can be far more hazardous (as it can compromise the entire system and not just specific users), is not.

Please consider changing it.

Regards,

Gil Cohen
Reserach director & Application security SME
CYE (cyesec)

**Comment by infosecdad** [comment]
Gil,
Thank you for the feedback, it's much appreciated.

Yes, there are CWEs that could fit in multiple categories; we moved them back and forth many times trying to find a balance. 
All of the CWEs in the Insecure Design are related as the CWE documentation mentioned their introduction is in the design/architecture phase where it was the lack of planning for the control as the root cause.

For malicious file upload, if I look at the data for it to be standalone, there isn't enough to justify it in the Top 10 by itself.
In the data submitted, out of over 367k applications tested, it was found in less than 1% (3.3k) of those applications.
In the industry survey, it was #5 in the list of CWEs that should be considered for addition to the Top 10.
The CWE-434 Unrestricted Upload of File with Dangerous Type is actually in the Top 10 under the A4:2021 Insecure Design list of CWEs in that category.

Thanks,
Brian

**Comment by chrisdlangton** [comment]
First: I don't support adding `malicious file upload` but `A4 Insecure design` is extremely confusing and out of place.

OWASP SAMM, ASVS, and the cheatsheet series are great places to raise awareness of `Insecure design` but the Top 10 is a  list of application 'weaknesses' or the way it has been extensively used and is best defined as 'attack vectors' in a threat modelling exercise.

`Insecure design` generally speaks to lack of `secure design`, frankly it covers the entire list of other 9, so why is there a deviation for A4? what exactly is the weakness or attack vector? All other items in the list are tangible, but A4 can be interpreted in a million and 1 ways

We need A4 to have an action the reader can take away.
We need to be able to teach defenders how to mitigate each item on the list, and A4 can be taught as "do the other 9 and A4 is done too" or "just design your application better" which can be ticked off because we had a meeting about it and call that a security review and our entire secure design strategy TICK! we're done.

Yes, I read the entire A4 page, specifically "How to Prevent" makes my entire argument valid. If you just secure harder you address A4 and are secure from attacks leveraging A4.. no.. that is total nonsense - but all other 9 on the list have a prevention that makes sense and actually prevents the item.

We can do everything on A4 but what was actually prevented after we do these activities? It is intangible, did it prevent anything? what was that exactly?

Yes I agree with the 3 scenarios, in fact I would agree if all scenarios from the other 9 were also listed as scenarios in A4!  

You can easily make any argument why A4 is important, and I will agree with every single argument you make I am sure.

but that does not make it valuable for A4 in the Top 10 now does it? 

We need to ask ourselves: what is the value of the Top 10? How is it used?

There is a tonne of Mapped CWEs here.. 
If you made a Top 10 and removed A4, you can essentially make an entire project around A4 (in fact that is exactly what other OWASP projects do!)

So let's make A4 something that fits into the theme of the top 10
Let's focus
And I would love to make some productive recommendations IF they we are open to dropping A4 entirely as it is and rethink what it means to be on the top 10. In context to the other 9, the top 10 is clear and consistent.

By adding A4 we undermine the entire effort and turns people away.

**Comment by gilcye** [comment]
I totally agree with @chrisdlangton. A4 is currently almost like saying "A4 - comply with OWASP top 10, preferably as soon as possible in the design phase". It too confusing. I'm not sure that it would turn people away, I think people would disregard A4, categorize all relevant CWEs as the other matching categories and effectively turn it into OWASP top 9.  Alternatively people could exploit it, fix just one of the issues mentioned in A4 and say that they comply with A4 entirely, and it is too broad. Scanners can check just one of the issues in A4 and say that they test it. I don't think that it would really promote secure design and shift-left... SDLC practices should preach for this.

**Comment by gilcye** [comment]
As of the malicious file upload vulnerability, I thank you @infosecdad for the sharing the information that lead you to that decision. Can you please also share what are the other 4 issues the are higher in the list of proffered CWE to be added to the top 10? I'll tell you why I ask you: It's not only me. I'm a member in an Israeli application security group and other expressed the same feeling about malicious file upload. I know it is not as common as CSRF was, but I believe it that due to its potential hazardous consequences that can lead to RCE and total server takeover, it should have its place.
And I believe that even if you save your uploads in an AWS S3 repository and enable uploading (and downloading) of EICAR for example, this could also be categorized as this vulnerability (lack of anti-virus scan of uploaded content). Although this would not lead to RCE, it could lead to client side attacks and I believe it would greatly increase the statistics of this vulnerability as there are *not really* physical files, but it is still the same issue.

**Comment by infosecdad** [comment]
Here are the top 8 survey results:
Server-Side Request Forgery (SSRF) [CWE-918] | 623
Use of Unmaintained Third Party Components [CWE-1104] | 462
Insufficient Logging and Monitoring [CWE-223/778] | 421
Unprotected Storage of Credentials [CWE-256] | 403
Unrestricted Upload of File with Dangerous Type [CWE-434] | 319
Excessive Attack Surface [CWE-1125] | 301
Inclusion of Functionality from Untrusted Control Sphere (3rd Party Content) [CWE-829] | 297
Insecure Build and/or Deployment Environment [No CWE] | 285

I understand your position about specific vulnerabilities based on your experience, you aren't the only one. However, per our process, I can't just add it in on its own. Neither the contributed data, nor the survey supports it. That said, the CWE is in the A4 category because typically it's due to the lack of a control defined at design time to prevent a malicious file from upload or execution.

Separately, there is a difference between Secure Design and Secure Implementation, and why we have (design) "flaw" vs. (implementation) "defect". A4 is not "everything". A4 is about the specific activity and mindset needed to understand that a security control is needed and where. The others are more in line with implementation; either the wrong control, or a weak control, etc. If you have insecure design, secure implementation is still vulnerable. If you have a secure design, you can still mess up the implementation.

**Comment by drwetter** [comment]
Question (OT) and maybe I missed that. The current draft: is that also risk based or what is that supposed to based upon?

**Comment by infosecdad** [comment]
Yes, the current draft is risk based from the data contributed and CVSS sub-scores.  Closing this issue.

**Comment by drwetter** [comment]
where can I find the usual / updated sheet for this?
