### ISSUE TITLE
A7 Feedback:insufficient attack protection is a control, not a risk. Replace it with deserialization vulnerabilities -  from Josh Grossman

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#60]
- A7 — Insufficient Attack Protection: This is a control, not a risk. It belongs in the top 10 proactive controls and not here.
- A7 should instead be Deserialisation Vulnerabilities because:
  - These issues have been around for a long time and have never received enough attention. They only really came to light in 2015 and are still poorly understood.
  - They are hard to understand and hard to casually exploit, especially within the confined time-frame of security testing.
  - They clearly affect a number of heavily used languages.
  - The severity is often critical leading to full Remote Code Execution on the web server, usually from the external Internet.
  - There are plenty of off-the-shelf products which are vulnerable to this. Some of them have been patched to fix it, the older ones have not.
  - Fixing the issue is not always straightforward or trivial.

21.	Josh Grossman

**Comment by itscooper** [comment]
> This is a control, not a risk

I would argue that a lack of a control, or an insufficiency in a control, poses a risk, and is therefore valid to be considered for inclusion in the OWASP Top Ten.

> should instead be Deserialisation Vulnerabilities

I agree this should also be considered, and I think that it should be an option on the survey that's being discussed, so that other members of the community can weigh-in.

**Comment by jmanico** [comment]
+1 Very reasonable logic here.

--
Jim Manico
@Manicode

**Comment by sslHello** [comment]
I think Deserialisation is too specific to be an individual topic.
I'd suggest to include it into A10, see #75:
I have no evidence to support this, but it seems that this vulnerability is more likely to show up in API communications than traditional web applications (e.g. used for parsing cookies). In APIs there may be a false sense of feeled 'internal
communication' that might beguile into using it. Particularily this might happen if the client app is also provided.
In general it looks like a special kind of injection to the runtime environment/the library that is used. But input validation seems NOT to completely mitigate the risk as bypassing ad-hoc SecurityManagers seems to be possible by design, see e.g. [GOD16-Deserialization.pdf](https://www.owasp.org/images/7/71/GOD16-Deserialization.pdf), [OWASP Deserialization Cheat Sheet](https://www.owasp.org/index.php/Deserialization_Cheat_Sheet)
As far as I see you'll get vulnerable by using this feature for external or public communication...
For issues if it is used in classical web applications e.g. cookies, hidden variables etc it could be mentioned in '+F-Details About Risk Factors', see #79

**Comment by gilzow** [comment]
> I think Deserialisation is too specific to be an individual topic.
But how is that any more or less specific than A3 - XSS, or A8 - CSRF?

> I'd suggest to include it into A10, see #75: I have no evidence to support this, but it seems that this vulnerability is more likely to show up in API communications than traditional web applications

I would respectfully disagree.  I've seen deserialization happen in multiple areas inside a web app, as well as in frontend SPAs. Only mentioning it in A10 would be the equivalent of only mentioning SQL injection in A10.

**Comment by tghosth** [comment]
Thanks for the feedback guys!

> I would argue that a lack of a control, or an insufficiency in a control, poses a risk, and is therefore valid to be considered for inclusion in the OWASP Top Ten.

@itscooper: The problem that I have with this is that it becomes circular logic. The OWASP Top 10 states that it is a list of risks. Controls are put in place to address risks, if you start turning a lack of a control into a risk, you lose sight of what the control is trying to prevent.

In addition, including a control in this list means that companies start looking at how they can comply with the control in the easiest way possible rather than assessing the actual risk which they are trying to control.

> I agree this should also be considered, and I think that it should be an option on the survey that's being discussed, so that other members of the community can weigh-in.

@itscooper. I hope so, I know @davewichers also included it as a possible candidate.

> > I'd suggest to include it into A10, see #75: I have no evidence to support this, but it seems that this vulnerability is more likely to show up in API communications than traditional web applications

> I would respectfully disagree. I've seen deserialization happen in multiple areas inside a web app, as well as in frontend SPAs. Only mentioning it in A10 would be the equivalent of only mentioning SQL injection in A10.

@sslHello I agree with @gilzow here.

Additionally, whilst I agree it is very specific, it is also a very unusual and dangerous issue that I think deserves more publicity.

**Comment by Neil-Smithline** [comment]
Related to https://github.com/OWASP/Top10/issues/57

**Comment by HoLyVieR** [comment]
> I think Deserialisation is too specific to be an individual topic.

I disagree that it's a vulnerability that's too specific as :
 - it affects lots of commonly used language (ex.: Java, Python, PHP, Node.JS, Ruby, etc.). 
 - it affected lots of big product (JBoss, Tomcat, Wordpress, etc.)
 - it affects lots of framework and technology (RMI, JMS, Spring Remoting, YAML, pickle, PHP unserialize, node-serialize, etc. )

The commonness of this type of vulnerability is in my opinion underestimated as it's a relatively new type of vulnerability.

**Comment by tghosth** [comment]
@itscooper, @vanderaj (tagged because I know you also made this point)

> I can typically break down the door and loot the kingdom without anyone batting an eyelid.

So part of me wants to agree with that but I find myself asking; what is a "just the top 10" company really going to do with that information?

Are they going to try simple IP/user account blocking or throwing up CAPTCHAs and hope that a) the attacker won't just change IP/user account and b) blocking the IP/user account won't break stuff for other people?

Are they going to be able to distinguish between a standard Burp scan just spray-gunned against an application and a successful SQL injection which is sucking out their database?

When a company has good internal network level logging and detective controls, they are in a position to isolate and halt an attack occurring internally. I am just struggling to see the same benefits against an external attacker.

I think that detection/response is an important consideration for a more mature company or if you are building an application from scratch [and want to build controls in from the start](https://www.owasp.org/index.php/OWASP_Proactive_Controls) but for the average company that is just trying to get its PCI compliance certificate, I cannot currently see a practical way in which they could benefit from this without a massive investment and/or making significant changes to existing applications and wading through loads of false positives.

This is really a thought in progress so I am keen to get your feedback as well.

**Comment by vanderaj** [comment]
This risk is going to be removed as per community feedback at the Project Summit, survey data and revised data call. Thank you for your input on this matter.
