### ISSUE TITLE
Forward Looking Issues 

### ISSUE THREAD

**Issue by raesene** [OWASP/Top10#85]
When I read through the "forward looking" survey I was a little surprised at some of the inclusions and omissions in the options available.

Some of the inclusions are old security issues that don't feel much like forward looking items at all.  Mass assignment is 10+ years old now, XXE is even older than that and cryptographic failures ....

Also if the project is about vulnerability categories and not risks,  "insufficient monitoring and logging" feels a bit out of place?

In terms of omissions, I noted that any mention of lacking proactive controls has been dropped (which was, I felt, the essence of the proposed A7).  I'm a little surprised that that's been dropped as even being an option on the survey given logging and monitoring is still present?

**Comment by borischen** [comment]
I will also echo the concern here.

Given proactive controls were on the table a few weeks ago and if the intent is to get feedback from others in the industry, then why are things being left off the survey which prevents people from voting for what they want?

It gives the impression that we simply go with the most vocal advocates, rather than providing the opportunity of letting others in the community to participate in the process.

**Comment by bchurchill** [comment]
My two cents: forward looking doesn't mean 'novel or new', rather it means, 'these vulnerabilities are underestimated understood and going to grow'.

**Comment by Neil-Smithline** [comment]
"Forward looking" is a phrase that tries to capture that they will be chosen using more intuition than the other, mainly statistic based entries.

**Comment by vanderaj** [comment]
As A7 and A10 are no longer in the OWASP Top 10, and as the OWASP Project Summit decided upon up to two forward looking *vulnerabilities* will be allowed to be included as long as data supports it either directly or via survey, this issue will be closed pending the data call being finalized.
