### ISSUE TITLE
Add Serialization Vulnerabilities to Top 10

### ISSUE THREAD

**Issue by borischen** [OWASP/Top10#92]
See #39

This includes not only language-native serialization, like CVE-2015-4852 (java), but also data serialization formats such as JSON, YAML, and XML. 

References:
* Language-specific Serialization Exploits - https://www.slideshare.net/frohoff1/appseccali-2015-marshalling-pickles
* Apache Commons Serialization - https://blogs.apache.org/foundation/entry/apache_commons_statement_to_widespread
* XML RCE - http://www.pwntester.com/blog/2013/12/23/rce-via-xstream-object-deserialization38/
* JSON Serialization Attacks - https://www.blackhat.com/docs/us-17/thursday/us-17-Munoz-Friday-The-13th-Json-Attacks.pdf
* RCE via YAML on Ruby - http://blog.codeclimate.com/blog/2013/01/10/rails-remote-code-execution-vulnerability-explained/
* Recent Struts RCE - https://lgtm.com/blog/apache_struts_CVE-2017-9805_announcement

**Comment by riramar** [comment]
@joaomatosf what do you think about that? :D

**Comment by joaomatosf** [comment]
Hi @riramar =D

I agree with this issue. 

As we all know, CWE-502 - Deserialization of Untrusted Data (what usually includes Object Injection + Property-Oriented Programming - POP) affects most major web technologies for many years. Additionally, in most cases, this has the most severe impact (easy for exploit in many cases, widespread, easy to detect and leads to remote code execution).

Also, this type of vulnerability affects not only the application itself, but can also persist in librarians or on the platform itself (very persistent).

This has been used in many campaigns for ransomware propagation and cyber espionage. For instance, see the cases of Samas (where they used the [JexBoss](https://github.com/joaomatosf/jexboss)) and the San Francisco Muni System.

Just to mention, at least since 2010 this is the most prevalent vulnerability class in web applications that lead to RCE in PHP environments and since 2013 in Java.

But anyway, I stopped paying attention to OWASP TOP 10 years ago.

=]

**Comment by jmanico** [comment]
> But anyway, I stopped paying attention to OWASP TOP 10 years ago.

Welcome back. We appreciate the expert attention. Please continue
letting us know how you think the OWASP Top Ten could be better.

Aloha, Jim

**Comment by Neil-Smithline** [comment]
@joaomatosf if you haven't already, we'd appreciate you taking the survey at https://docs.google.com/forms/d/e/1FAIpQLSdy-ok2o_BBHsZn0r5WfwxOkCv1CQ4nKZ8VSmD6bYq-du22hg/viewform

**Comment by joaomatosf** [comment]
@jmanico thanks =]

@Neil-Smithline done

Equifax liked this =D

**Comment by vanderaj** [comment]
This is being assigned to @infosecdad as it relates to the Data Call being finalized. Let's see where the data lands.

**Comment by vanderaj** [comment]
This is done
